# [START django_app]
# maratron google app engine 
runtime: python37

instance_class: F4_1G
handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static_root
- url: /media
  static_dir: media
# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
automatic_scaling:
  min_instances: 4
  max_instances: 10
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: 30ms
  max_pending_latency: automatic
# [END django_app]
