# Generated by Django 2.2 on 2019-04-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maratron',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('song', 'Song'), ('poem', 'Poem')], default='song', max_length=4)),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('contents', models.FileField(upload_to='contents')),
                ('audio', models.FileField(upload_to='audio')),
            ],
        ),
    ]
