# Generated by Django 2.2 on 2019-05-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maratron',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('한국어', '한국어'), ('영어', '영어')], default='한국어', max_length=4)),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('contents', models.FileField(upload_to='contents')),
                ('audio', models.FileField(upload_to='audio')),
            ],
        ),
    ]
